// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(WriteDataContext))]
    partial class WriteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.DeliveryPersonAggregate.Entities.CnhType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("CnhTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A"
                        },
                        new
                        {
                            Id = 2,
                            Description = "B"
                        },
                        new
                        {
                            Id = 3,
                            Description = "AxB"
                        });
                });

            modelBuilder.Entity("Domain.Models.DeliveryPersonAggregate.Entities.DeliveryPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<short>("CnhType")
                        .HasColumnType("smallint")
                        .HasColumnName("CnhType");

                    b.HasKey("Id");

                    b.ToTable("DeliveryPersons", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MotorcycleAggregate.Entities.Motorcycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Motorcycles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.RentalAggregate.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("numeric(10,2)");

                    b.Property<short>("Days")
                        .HasColumnType("smallint");

                    b.Property<int>("DeliveryPersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("date");

                    b.Property<int>("MotorcycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPersonId");

                    b.HasIndex("MotorcycleId");

                    b.ToTable("Rentals", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DeliveryPersonAggregate.Entities.DeliveryPerson", b =>
                {
                    b.OwnsOne("Domain.Models.Shared.ValueObjects.UIdValue", "UId", b1 =>
                        {
                            b1.Property<int>("DeliveryPersonId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("UId");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.OwnsOne("Domain.Models.DeliveryPersonAggregate.ValueObjects.CnpjValue", "Cnpj", b1 =>
                        {
                            b1.Property<int>("DeliveryPersonId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar")
                                .HasColumnName("Cnpj");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.OwnsOne("Domain.Models.DeliveryPersonAggregate.ValueObjects.ImageUrlValue", "CnhImageUrl", b1 =>
                        {
                            b1.Property<int>("DeliveryPersonId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .HasMaxLength(1024)
                                .HasColumnType("varchar")
                                .HasColumnName("CnhImageUrl");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.OwnsOne("Domain.Models.DeliveryPersonAggregate.ValueObjects.NameValue", "Name", b1 =>
                        {
                            b1.Property<int>("DeliveryPersonId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar")
                                .HasColumnName("Name");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.OwnsOne("Domain.Models.DeliveryPersonAggregate.ValueObjects.NumberValue", "CnhNumber", b1 =>
                        {
                            b1.Property<int>("DeliveryPersonId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("CnhNumber");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.Navigation("CnhImageUrl");

                    b.Navigation("CnhNumber")
                        .IsRequired();

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("UId")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.MotorcycleAggregate.Entities.Motorcycle", b =>
                {
                    b.OwnsOne("Domain.Models.Shared.ValueObjects.UIdValue", "UId", b1 =>
                        {
                            b1.Property<int>("MotorcycleId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("UId");

                            b1.HasKey("MotorcycleId");

                            b1.ToTable("Motorcycles");

                            b1.WithOwner()
                                .HasForeignKey("MotorcycleId");
                        });

                    b.OwnsOne("Domain.Models.MotorcycleAggregate.ValueObjects.ModelValue", "Model", b1 =>
                        {
                            b1.Property<int>("MotorcycleId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("Model");

                            b1.HasKey("MotorcycleId");

                            b1.ToTable("Motorcycles");

                            b1.WithOwner()
                                .HasForeignKey("MotorcycleId");
                        });

                    b.OwnsOne("Domain.Models.MotorcycleAggregate.ValueObjects.PlateValue", "Plate", b1 =>
                        {
                            b1.Property<int>("MotorcycleId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("Plate");

                            b1.HasKey("MotorcycleId");

                            b1.ToTable("Motorcycles");

                            b1.WithOwner()
                                .HasForeignKey("MotorcycleId");
                        });

                    b.Navigation("Model")
                        .IsRequired();

                    b.Navigation("Plate")
                        .IsRequired();

                    b.Navigation("UId")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.RentalAggregate.Entities.Rental", b =>
                {
                    b.HasOne("Domain.Models.DeliveryPersonAggregate.Entities.DeliveryPerson", null)
                        .WithMany()
                        .HasForeignKey("DeliveryPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.MotorcycleAggregate.Entities.Motorcycle", null)
                        .WithMany()
                        .HasForeignKey("MotorcycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.Shared.ValueObjects.UIdValue", "UId", b1 =>
                        {
                            b1.Property<int>("RentalId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("UId");

                            b1.HasKey("RentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalId");
                        });

                    b.Navigation("UId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
